// Copies Loadout's third-party browser files out of node_modules and builds
// its icon sprite. Run `npm install && npm run vendor` after bumping a version
// in package.json, then commit the result: the app itself has no build step.
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { buildSync } from 'esbuild';

const root = path.dirname(path.dirname(new URL(import.meta.url).pathname));
const nm = (p) => path.join(root, 'node_modules', p);
const out = (p) => path.join(root, 'apps/loadout', p);
const version = (pkg) => createRequire(import.meta.url)(nm(`${pkg}/package.json`)).version;
const stripMap = (s) => s.replace(/\n\/\/# sourceMappingURL=.*\s*$/, '\n');

const files = [
  ['gun/gun.js', '../shared/gun.js'],
  ['qrcode-generator/dist/qrcode.mjs', '../shared/qrcode.mjs'],
  ['marked/lib/marked.esm.js', 'vendor/marked.esm.js'],
  ['dompurify/dist/purify.es.mjs', 'vendor/purify.es.mjs'],
  ['qrcode-generator/dist/qrcode.mjs', 'vendor/qrcode.mjs'],
];
for (const [from, to] of files) {
  fs.mkdirSync(path.dirname(out(to)), { recursive: true });
  fs.writeFileSync(out(to), stripMap(fs.readFileSync(nm(from), 'utf8')));
}

// Icon sprites: <svg><use href="icons.svg#name"/></svg>
function sprite(file, icons) {
  const symbols = icons.map((name) => {
    const svg = fs.readFileSync(nm(`lucide-static/icons/${name}.svg`), 'utf8');
    const body = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').replace(/\s*\n\s*/g, '');
    return `<symbol id="${name}" viewBox="0 0 24 24">${body}</symbol>`;
  });
  fs.writeFileSync(
    path.join(root, file),
    `<svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">\n<!-- Lucide icons (ISC) -->\n${symbols.join('\n')}\n</svg>\n`,
  );
  return icons.length;
}
const ICONS = [
  'plus', 'minus', 'check', 'x', 'share-2', 'ellipsis', 'trash-2', 'lock', 'globe', 'list-checks',
  'notebook-pen', 'package', 'user', 'settings', 'copy', 'qr-code', 'grip-vertical', 'chevron-left',
  'cloud', 'cloud-off', 'download', 'upload', 'key-round', 'eye', 'pencil', 'link', 'sun', 'moon',
  'log-out', 'shield', 'refresh-cw', 'external-link', 'pin', 'pin-off', 'search', 'file-text',
];
const HUB_ICONS = ['list-checks', 'message-square-lock', 'sticky-note', 'send', 'gamepad-2', 'git-branch', 'arrow-up-right', 'radio-tower'];
const iconCount = sprite('apps/loadout/icons.svg', ICONS) + sprite('hub/icons.svg', HUB_ICONS);

// The nostr bundle: nostr-tools and its noble/scure dependencies in one ESM file.
buildSync({
  entryPoints: [path.join(root, 'scripts/nostr-entry.mjs')],
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: 'es2022',
  minify: true,
  legalComments: 'none',
  outfile: path.join(root, 'apps/shared/nostr.mjs'),
  banner: { js: `// nostr-tools ${version('nostr-tools')} (Unlicense) with @noble/curves, @noble/hashes, @noble/ciphers, @scure/base (MIT). Built by scripts/vendor.mjs; see apps/shared/LICENSES.md.` },
});
const nostrSize = fs.statSync(path.join(root, 'apps/shared/nostr.mjs')).size;

fs.writeFileSync(
  path.join(root, 'apps/shared/LICENSES.md'),
  `# Third-party files in apps/shared

Generated by \`npm run vendor\` (scripts/vendor.mjs). Do not edit by hand.

| File | Package | License |
|------|---------|---------|
| nostr.mjs | nostr-tools ${version('nostr-tools')} | Unlicense |
| nostr.mjs | @noble/curves ${version('@noble/curves')}, @noble/hashes ${version('@noble/hashes')}, @noble/ciphers ${version('@noble/ciphers')}, @scure/base ${version('@scure/base')} | MIT |
| gun.js | gun ${version('gun')} | Zlib OR MIT OR Apache-2.0 |
| qrcode.mjs | qrcode-generator ${version('qrcode-generator')} | MIT |
`,
);

const licenses = `# Third-party files

Generated by \`npm run vendor\` (scripts/vendor.mjs). Do not edit by hand.

| File | Package | License |
|------|---------|---------|
| marked.esm.js | marked ${version('marked')} | MIT |
| purify.es.mjs | dompurify ${version('dompurify')} | MPL-2.0 OR Apache-2.0 |
| qrcode.mjs, ../../shared/qrcode.mjs | qrcode-generator ${version('qrcode-generator')} | MIT |
| ../icons.svg, hub/icons.svg | lucide-static ${version('lucide-static')} | ISC |
`;
fs.writeFileSync(out('vendor/LICENSES.md'), licenses);
console.log(`vendored ${files.length} files, ${iconCount} icons and nostr.mjs (${Math.round(nostrSize / 1024)} KB)`);
